const Keys = {
  API_URL: import.meta.env.VITE_API_URL,
  FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: import.meta.env
    .VITE_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_MESSAGING_APPID: import.meta.env.VITE_FIREBASE_MESSAGING_APPID,
  FIREBASE_MESSAGING_MEASUREMENT_ID: import.meta.env
    .VITE_FIREBASE_MESSAGING_MEASUREMENT_ID,
};

export default Keys;
